---
  
- name: Common configuration for all hosts
  hosts: all
  gather_facts: yes
    
- name: Configuring HAproxy
  hosts: HAproxy
  become: true
  become_method: sudo
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        update_cache: yes
        state: latest
    
    - name: Configure HAproxy for load balancing
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart HAproxy service
      service:
        name: haproxy
        state: restarted
    
- name: Web Server Configuration
  hosts: webservers
  become: yes
  become_method: sudo
  tasks:     
    - name: Refresh apt cache
      apt:
        update_cache: yes
    
    - name: Install Python3, pip3, and venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
    - name: Installing flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Installing Gunicorn
      apt:
        name: gunicorn

    - name: Copy Application2.py
      copy:
        src: /$PWD/application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Running Flask application
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app
  
    - name: Start Flask app using Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 application2:app
      args:
        chdir: /home/ubuntu
