- hosts: all
  gather_facts: yes

- name: Configuring HAproxy
  hosts: HAproxy
  become: yes
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        update_cache: yes
        state: latest

    - name: Configure HAproxy load balancing
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'

    - name: Restart HAproxy
      service:
        name: haproxy
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Install Nginx for UDP services
      apt:
        name: nginx
        state: latest

    - name: Configure Nginx UDP port
      template:
        src: nginxport.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'
        create: yes

    - name: Configure Nginx for UDP load balancing
      template:
        src: nginxudp.conf
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        create: yes

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
        daemon_reload: yes

- name: Web Server configuration
  hosts: webservers
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install NGINX and Flask dependencies
      apt:
        name: ['nginx', 'python3-flask', 'python3-pip']
        state: present

    - name: Install Flask via pip3
      pip:
        name: flask
        executable: pip3

    - name: Install Gunicorn
      pip:
        name: gunicorn
        executable: pip3

    - name: Copy Flask application code
      copy:
        src: ./application2.py   # Ensure this file exists in your Ansible directory
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Run Flask app with Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 application2:app
      args:
        chdir: /home/ubuntu



  
