---
  
- name: Common configuration for all hosts
  hosts: all
  gather_facts: yes
    
- name: Configuring HAproxy
  hosts: HAproxy
  become: true
  become_method: sudo
  tasks:
    - name: Install HAproxy
      apt:
        name: haproxy
        update_cache: yes
        state: latest
    
    - name: Configure HAproxy for load balancing
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart HAproxy service
      service:
        name: haproxy
        state: restarted
    
- name: Web Server Configuration
  hosts: webservers
  become: yes
  become_method: sudo
  tasks:     
    - name: Refresh apt cache
      apt:
        update_cache: yes
    
    - name: Install pip3
      apt:
        name: python3-pip
        state: latest
  
    - name: Install Flask
      pip:
        executable: pip3
        name: flask
        state: latest
        
    - name: Install Gunicorn
      pip:
        executable: pip3
        name: gunicorn   
        state: latest
  
    - name: Copy Flask application
      copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Run Flask application with Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 application2:app
      args:
        chdir: /home/ubuntu
  
- name: Testing HAProxy Load Balancing
  hosts: HAproxy
  become: yes
  tasks:
    - name: Test HAProxy 1st time
      shell: curl localhost
register: output1
    - debug: var=output1.stdout
      
    - name: Test HAProxy 2nd time
      shell: curl localhost
      register: output2
    - debug: var=output2.stdout
  
    - name: Test HAProxy 3rd time
      shell: curl localhost
      register: output3
    - debug: var=output3.stdout
