# haproxy configuration
- hosts: all
  gather_facts: true
- hosts: HAproxy
  become: true

  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: Installing HAPROXY
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: /$PWD/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
 
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
        
- hosts: webservers
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: Install Python3, pip3, and venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
    - name: Installing flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Installing Gunicorn
      apt:
        name: gunicorn

    - name: Copy Application2.py
      copy:
        src: /$PWD/application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Running Flask application
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app
